---
title: "web_scraping_subway"
author: "Brian"
date: "10/26/2024"
output: html_document
---

# Loading in rvest package needed for web-scraping

```{r}
library(dplyr)
library(rvest)
```

# Reading in the html of the subway website

```{r}
subway <- "https://restaurants.subway.com"

## LINK SHOULD NOT HAVE A BACK SLASH AT THE END!!!!!!!!!
```



```{r}
<<<<<<< HEAD
addressParser <- function(url) {                                   # Creating a function for parsing addresses on the Subway website
  links <- read_html(url) %>%                                                          # Read in the html url and referring it to links in the function
            html_elements(".Directory-listLink") %>%     # Specifying the css selector to refer to the country link
            html_attr("href")
            #print(url)
            link <- paste(url, links, sep = "/")                   ## REPEATING HREFS IS BECAUSE OF RECURSIVE LINKS VARIABLE
            #print(link)
  if (url == "https://restaurants.subway.com/index.html") {
    dead_link <- paste(url, sep = "")
    #print(dead_link)
    NA <- dead_link
    
   
||||||| 09161ef
addressParser <- function(url) {                                   # Creating a function for parsing addresses on the Subway website
  links <- read_html(url) %>%
  
    
                                                                    # Read in the html url and referring it to links in the function
            html_elements(".Directory-listLink") %>%     # Specifying the css selector to refer to the country link
            html_attr("href")
  print(url)
  
  link <- paste(url, links, sep = "/")                   ## REPEATING HREFS IS BECAUSE OF RECURSIVE LINKS VARIABLE
  print(link)
  if (url == "https://restaurants.subway.com/index.html") {
    dead_link <- paste(url, sep = "")
    #print(dead_link)
    NA <- dead_link
    
   
=======
# Read in the html url and referring it to links in the function
      # if (html_elements(".Directory-listLink") == html_elements(".Directory-listLink")) {
              # element <- html_elements(hrefs,".Directory-listLink")     # Specifying the css selector to refer to the country link
              # html_attr(element, "href")
     #          new_x <- read_html(x) %>% html_nodes(".tittleArticuloOpinion") %>% html_text
     # if(length(new_x) == 0) 
     #    new_x <- read_html(x) %>% html_nodes(".nameColumnista") %>% html_text
#       } else {
#           other_element <- html_elements(hrefs,".Teaser-innerWrapper")
#           html_attr(other_element, "href")
# }
addressParser <- function(url) {                                
  hrefs <- read_html(url) %>%                                                          
    html_elements(".Directory-listLink") %>%     
    html_attr("href")
  formattedHrefs <- gsub("../", "", hrefs, fixed = TRUE)
  link <- paste(subway, formattedHrefs, sep = "/")        
  read_link <- read_html(link) %>% 
    if(html_elements(".Teaser-innerWrapper") == TRUE) {
       html_text2()
 
>>>>>>> 93c7a35b54dffada6464bc6a9084a262a0a183b5
  # print(link)
  } else if (url == "https://restaurants.subway.com/index.html") {
    NA
  } else if (length(hrefs) == 0) {
      url %>%
      read_html %>%
      html_element("#address") %>%
      html_text2()
    } else {
    c(lapply(link, addressParser), recursive = TRUE)      
   }
}
<<<<<<< HEAD
# # means id
#  <- subway %>%
#   html_elements("a")                                                # See html source code for data within this tag
# 
# sapply(urls, function (x) {
#   testcountryLink <- html_nodes("a .Directory-listLink") 
#   countryLink <- html_attr(x, "href")                               # Pulling the links that all pertain to a country through calling the attribute "href"
#   district_html <- read_html("https://restaurants.subway.com/austria")  # Right now Austria is hard-coded but eventually have to figure out a way to automate the reading of all countries (regexp?)
#                                                                         # Most countries are divided into districts which introduces 3 levels but some aren't, so they would have 2 levels (*might need an if statement or 2 scrapers)
#   districtLink <- html_attr(x, "href")
#   cityLink <- read_html("https://restaurants.subway.com/austria/bu")
#   city_html <- html_elements("c-address")
#   })
# 
# #sapply is the end goal for extracting string values
# #lapply is for lists
||||||| 09161ef
addressParser(subway)

# # means id
#  <- subway %>%
#   html_elements("a")                                                # See html source code for data within this tag
# 
# sapply(urls, function (x) {
#   testcountryLink <- html_nodes("a .Directory-listLink") 
#   countryLink <- html_attr(x, "href")                               # Pulling the links that all pertain to a country through calling the attribute "href"
#   district_html <- read_html("https://restaurants.subway.com/austria")  # Right now Austria is hard-coded but eventually have to figure out a way to automate the reading of all countries (regexp?)
#                                                                         # Most countries are divided into districts which introduces 3 levels but some aren't, so they would have 2 levels (*might need an if statement or 2 scrapers)
#   districtLink <- html_attr(x, "href")
#   cityLink <- read_html("https://restaurants.subway.com/austria/bu")
#   city_html <- html_elements("c-address")
#   })
# 
# #sapply is the end goal for extracting string values
# #lapply is for lists
=======
```


```{r}
res <- addressParser(subway)
res


### different formatted address when running again
```


```{r}
library(dplyr)
library(rvest)
```

```{r}
subway <- "https://restaurants.subway.com"
```


```{r}
addressParser <- function(url) {                                
  hrefs <- read_html(url) %>%                                                          
    html_elements(".Directory-listLink") %>%     
    html_attr("href")
  formattedHrefs <- gsub("../", "", hrefs, fixed = TRUE)
  link <- paste(subway, formattedHrefs, sep = "/")
  print(link)
  if (length(html_elements(".Teaser-innerWrapper")) > 0) {
    url %>%
      read_html %>%
      html_element(".c-address") %>%
      html_text2()
     
  # print(link)
  } else if (url == "https://restaurants.subway.com/index.html") {
    NA
  } else if (length(hrefs) == 0) {
    url %>%
      read_html %>%
      html_element("#address") %>%
      html_text2()
  } else {
    c(lapply(link, addressParser), recursive = TRUE)      
  }
}
```


```{r}
addressParser(subway)

>>>>>>> 93c7a35b54dffada6464bc6a9084a262a0a183b5
```
<<<<<<< HEAD


```{r}
addressParser(subway)
```

||||||| 09161ef
=======
<!-- library(dplyr) -->
<!-- library(rvest) -->

<!-- subway <- "https://restaurants.subway.com" -->

<!-- addressParser <- function(url) {                                 -->
<!--   hrefs <- read_html(url) %>%                                                           -->
<!--     html_elements(".Directory-listLink") %>%      -->
<!--     html_attr("href") -->
<!--   formattedHrefs <- gsub("../", "", hrefs, fixed = TRUE) -->
<!--   link <- paste(subway, formattedHrefs, sep = "/") -->

<!--   other_address <- read_html(url) %>% -->
<!--     html_elements(".Teaser-innerWrapper") -->
<!--   if (length(other_address) > 0) { -->
<!--     hrefs <- read_html(url) %>%                                                           -->
<!--       html_elements(".Teaser-title") %>%      -->
<!--       html_attr("href") -->

<!--     # print(link) -->
<!--   } else if (url == "https://restaurants.subway.com/index.html") { -->
<!--     NA -->
<!--   } else if (length(hrefs) == 0) { -->
<!--     url %>% -->
<!--       read_html %>% -->
<!--       html_element("#address") %>% -->
<!--       html_text2() -->
<!--   } else { -->
<!--     c(lapply(link, addressParser), recursive = TRUE)       -->
<!--   } -->
<!-- } -->

<!-- addressParser(subway) -->
>>>>>>> 93c7a35b54dffada6464bc6a9084a262a0a183b5
